package lotto.domain;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class AutoGeneratedTicketNumbers extends Numbers {

    public AutoGeneratedTicketNumbers(Set<Number> numbers) {
        super(numbers);
        if (numbers.size() != 6) {
            throw new RuntimeException("로또 번호는 중복되지 않는 6개의 수로 구성되어야 합니다.");
        }
    }

    public AutoGeneratedTicketNumbers(List<Number> numbers) {
        this(new HashSet<>(numbers));
    }


}
