package lotto.domain;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LottoMachine {

    private final List<Numbers> tickets = new ArrayList<>();

    private final List<Number> numberPool;

    public LottoMachine(List<Number> numberPool) {
        this.numberPool = numberPool;
    }

    public List<AutoGeneratedTicketNumbers> generateTickets(int autoGenerateQuantity) {
        List<AutoGeneratedTicketNumbers> generatedTickets = new ArrayList<>();
        for (int i = 0; i < autoGenerateQuantity; i++) {
            Collections.shuffle(numberPool);
            generatedTickets.add(new AutoGeneratedTicketNumbers(numberPool.subList(0, 6)));
        }
        return generatedTickets;
    }

    public void registerTickets(List<? extends Numbers> tickets) {
        this.tickets.addAll(tickets);
    }

    public LottoResult getResult(WinningNumbers winningNumbers) {
        Map<Prize, Integer> result = new HashMap<>();
        for (Prize prize : Prize.values()) {
            result.put(prize, 0);
        }

        for (Numbers ticket : tickets) {
            Prize prize = winningNumbers.checkWinning(ticket);
            result.compute(prize, (key, oldValue) -> oldValue == null ? 0 : oldValue + 1);
        }

        double resultRate = PrizeCalculator.calculate(result);

        return new LottoResult(result, resultRate);
    }
}
